package io.agrest.it.fixture.cayenne.aggregate1.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.agrest.it.fixture.cayenne.aggregate1.A12;

/**
 * Class _A11 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _A11 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<A12> A2 = Property.create("a2", A12.class);

    public void setA2(A12 a2) {
        setToOneTarget("a2", a2, true);
    }

    public A12 getA2() {
        return (A12)readProperty("a2");
    }


}
