package io.agrest.it.fixture.cayenne.aggregate1.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.agrest.it.fixture.cayenne.aggregate1.A11;
import io.agrest.it.fixture.cayenne.aggregate1.A13;

/**
 * Class _A12 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _A12 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<List<A11>> A1S = Property.create("a1s", List.class);
    public static final Property<List<A13>> A3S = Property.create("a3s", List.class);

    public void addToA1s(A11 obj) {
        addToManyTarget("a1s", obj, true);
    }
    public void removeFromA1s(A11 obj) {
        removeToManyTarget("a1s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<A11> getA1s() {
        return (List<A11>)readProperty("a1s");
    }


    public void addToA3s(A13 obj) {
        addToManyTarget("a3s", obj, true);
    }
    public void removeFromA3s(A13 obj) {
        removeToManyTarget("a3s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<A13> getA3s() {
        return (List<A13>)readProperty("a3s");
    }


}
