package io.agrest.it.fixture.cayenne.aggregate1.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.agrest.it.fixture.cayenne.aggregate1.A12;
import io.agrest.it.fixture.cayenne.aggregate1.A14;

/**
 * Class _A13 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _A13 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> F = Property.create("f", String.class);
    public static final Property<A12> A2 = Property.create("a2", A12.class);
    public static final Property<List<A14>> A4S = Property.create("a4s", List.class);

    public void setF(String f) {
        writeProperty("f", f);
    }
    public String getF() {
        return (String)readProperty("f");
    }

    public void setA2(A12 a2) {
        setToOneTarget("a2", a2, true);
    }

    public A12 getA2() {
        return (A12)readProperty("a2");
    }


    public void addToA4s(A14 obj) {
        addToManyTarget("a4s", obj, true);
    }
    public void removeFromA4s(A14 obj) {
        removeToManyTarget("a4s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<A14> getA4s() {
        return (List<A14>)readProperty("a4s");
    }


}
