package io.agrest.it.fixture.cayenne.aggregate1.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.agrest.it.fixture.cayenne.aggregate1.A13;

/**
 * Class _A14 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _A14 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> F = Property.create("f", String.class);
    public static final Property<A13> A3 = Property.create("a3", A13.class);

    public void setF(String f) {
        writeProperty("f", f);
    }
    public String getF() {
        return (String)readProperty("f");
    }

    public void setA3(A13 a3) {
        setToOneTarget("a3", a3, true);
    }

    public A13 getA3() {
        return (A13)readProperty("a3");
    }


}
